name: mnpowerpages
favicon: null
layout_spectrum: 0.5550863880198449
typography_spectrum: 0.1951842769049108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5906694917939603
  lightness: 0.3257579365745187
  saturation: 0.49630568106658757
  rhythmicContrast: 0.8366266093216836
purpose: []
